# Generated by Django 4.2.29 on 2026-09-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('prestataire', 'Prestataire')], default='client', max_length=20),
        ),
    ]
