# Generated by Django 4.2.29 on 2026-09-09 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_date_suspension_user_suspendu'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_debut_plan',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_fin_plan',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('gratuit', 'Gratuit'), ('standard', 'Standard'), ('pro', 'Pro')], default='gratuit', max_length=20),
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('gratuit', 'Gratuit'), ('standard', 'Standard'), ('pro', 'Pro')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('methode', models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('virement', 'Virement bancaire'), ('especes', 'Espèces')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('actif', 'Actif'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement',
                'ordering': ['-date_demande'],
            },
        ),
    ]
