# Generated by Django 4.2.29 on 2026-09-09 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_date_debut_plan_user_date_fin_plan_user_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='methode',
            field=models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('virement', 'Virement bancaire')], max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('abonnement', 'Abonnement'), ('commission', 'Commission'), ('mission', 'Mission'), ('demande', 'Demande'), ('systeme', 'Système')], default='systeme', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('lien', models.CharField(blank=True, max_length=255)),
                ('est_lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-date_creation'],
            },
        ),
    ]
