# Generated by Django 4.2.29 on 2026-09-18 20:17

import apps.accounts.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0002_favorisdemande'),
        ('accounts', '0006_alter_abonnement_methode_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='competences',
            field=models.ManyToManyField(blank=True, related_name='prestataires_competents', to='demandes.categorie', verbose_name='Compétences'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('abonnement', 'Abonnement'), ('commission', 'Commission'), ('mission', 'Mission'), ('demande', 'Demande'), ('litige', 'Litige'), ('systeme', 'Système')], default='systeme', max_length=20),
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=120, verbose_name='Titre du projet')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), apps.accounts.validators.valider_taille_avatar], verbose_name='Image (optionnelle)')),
                ('url', models.URLField(blank=True, verbose_name='Lien externe (optionnel)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL, verbose_name='Prestataire')),
            ],
            options={
                'verbose_name': 'Projet (portfolio)',
                'ordering': ['-date_creation'],
            },
        ),
    ]
