# Generated by Django 4.2.29 on 2026-09-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=128, unique=True)),
                ('type', models.CharField(blank=True, max_length=64)),
                ('donnees', models.JSONField(blank=True, default=dict)),
                ('recu_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Événement webhook',
                'verbose_name_plural': 'Événements webhook',
                'ordering': ['-recu_le'],
            },
        ),
    ]
