# Generated by Django 4.2.29 on 2026-09-05 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('budget_min', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('lieu', models.CharField(blank=True, max_length=100)),
                ('a_distance', models.BooleanField(default=False)),
                ('urgence', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('en_cours', 'En cours (propositions)'), ('mission_active', 'Mission en cours'), ('cloturee', 'Clôturée')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='demandes.categorie')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande',
                'ordering': ['-date_creation'],
            },
        ),
    ]
