# Generated by Django 4.2.29 on 2026-09-18 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavorisDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='demandes.demande', verbose_name='Demande')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_demandes', to=settings.AUTH_USER_MODEL, verbose_name='Prestataire')),
            ],
            options={
                'verbose_name': 'Favori de demande',
                'verbose_name_plural': 'Favoris de demandes',
                'ordering': ['-date_creation'],
                'unique_together': {('prestataire', 'demande')},
            },
        ),
    ]
