# Generated by Django 4.2.29 on 2026-09-05 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('cloturee', 'Clôturée'), ('litige', 'Litige')], default='en_cours', max_length=20)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions_client', to=settings.AUTH_USER_MODEL)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='demandes.demande')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions_prestataire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mission',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=0, max_digits=12)),
                ('delais_jours', models.PositiveIntegerField(verbose_name='Délais (jours)')),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('envoyee', 'Envoyée'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='envoyee', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='demandes.demande')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proposition',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('methode', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('virement', 'Virement bancaire'), ('especes', 'Espèces')], default='especes', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='propositions.mission')),
            ],
            options={
                'verbose_name': 'Paiement',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='mission',
            name='proposition',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission', to='propositions.proposition'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField()),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_donnees', to=settings.AUTH_USER_MODEL)),
                ('cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_recues', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='propositions.mission')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.CheckConstraint(check=models.Q(('note__gte', 1), ('note__lte', 5)), name='note_1_5'),
        ),
    ]
