# Generated by Django 4.2.29 on 2026-09-08 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('methode', models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('virement', 'Virement bancaire'), ('especes', 'Espèces')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée')], default='en_attente', max_length=20)),
                ('date_limite', models.DateTimeField(verbose_name='Date limite de règlement')),
                ('date_declaration', models.DateTimeField(blank=True, null=True, verbose_name='Date de déclaration de règlement')),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation de paiement')),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='propositions.mission')),
            ],
            options={
                'verbose_name': 'Commission',
                'ordering': ['date_limite'],
            },
        ),
    ]
