# Generated by Django 4.2.29 on 2026-09-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0002_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='methode',
            field=models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('virement', 'Virement bancaire')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('virement', 'Virement bancaire')], default='mobile_money', max_length=20),
        ),
    ]
