# Generated by Django 4.2.29 on 2026-09-11 18:59

from django.db import migrations, models


def migrer_methodes(apps, schema_editor):
    """Convertit les anciennes valeurs de méthode vers les opérateurs ciblés."""
    Paiement = apps.get_model('propositions', 'Paiement')
    Commission = apps.get_model('propositions', 'Commission')
    for model, champ in ((Paiement, 'methode'), (Commission, 'methode')):
        for ancien, nouveau in (('mobile_money', 'mtn_momo'), ('especes', 'virement')):
            model.objects.filter(**{champ: ancien}).update(**{champ: nouveau})


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0003_alter_commission_methode_alter_paiement_methode'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='reference_payout',
            field=models.CharField(blank=True, max_length=64, verbose_name='Référence reversement (FedaPay)'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='donnees_webhook',
            field=models.JSONField(blank=True, default=dict, verbose_name='Événement webhook reçu'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='reference_txn',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Référence transaction (FedaPay)'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='methode',
            field=models.CharField(blank=True, choices=[('mtn_momo', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('celtis', 'Celtiis Cash'), ('virement', 'Virement bancaire')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='methode',
            field=models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('moov', 'Moov Money'), ('celtis', 'Celtiis Cash'), ('virement', 'Virement bancaire')], default='mtn_momo', max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('en_attente', 'En attente'), ('paye', 'Payé'), ('echec', 'Échec')], default='en_cours', max_length=20),
        ),
        migrations.RunPython(migrer_methodes, migrations.RunPython.noop),
    ]
