# Generated by Django 4.2.29 on 2026-09-18 19:10

import apps.propositions.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propositions', '0004_commission_reference_payout_paiement_donnees_webhook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Litige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(verbose_name='Motif du litige')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='litiges/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'webp']), apps.propositions.validators.valider_taille_piece], verbose_name='Pièce jointe (preuve)')),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('mediation', 'Médiation'), ('clos', 'Clos')], default='ouvert', max_length=20)),
                ('en_faveur', models.CharField(blank=True, choices=[('client', 'En faveur du client'), ('prestataire', 'En faveur du prestataire'), ('partage', 'Partage entre les deux parties')], max_length=20)),
                ('decision', models.TextField(blank=True, verbose_name='Décision de l’équipe')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='litige', to='propositions.mission')),
                ('signaleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litiges_signales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Litige',
                'ordering': ['-date_creation'],
            },
        ),
    ]
